name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
        # filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Install pnpm itself (required before use)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0  # You can use latest

      # Cache node_modules
      # Setup Node.js with pnpm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'


      # - run: npm ci
      # Install all dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright deps
        run: pnpm exec playwright install --with-deps

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: npx nx-cloud record -- echo Hello World
      # When you enable task distribution, run the e2e-ci task instead of e2e
      # Run lint, test, build, and e2e using Nx
      - name: Run lint, test, build, and e2e
        run: pnpm nx run-many -t lint test build e2e --projects=Admin-Portal,api,user-dashboard
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      # - run: npx nx fix-ci
      # Fix CI issues using Nx Cloud
      - name: Fix CI (Nx Cloud)
        if: always()
        run: pnpm nx fix-ci
